### PR TITLE
Better FHIR resource management for draft processes

### LINKED ISSUE #165: Can't add a New Extension to Existing Draft Process
I have an existing BPE process represented by it's ActivityDefinition. The status of the ActivityDefinition is `draft`. I would expect that I can add more Extensions, CodeSystems etc. 

However, if I start the BPE with my new JAR, containing the new Extension, the BPE tries to update the extension instead of creating it in the FHIR server. Because the Extension has no ID in this state, I get an NPE at: 

```
java.lang.NullPointerException: null
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.update(FhirResourceHandlerImpl.java:399) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.updateToDraft(FhirResourceHandlerImpl.java:387) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.fromDraft(FhirResourceHandlerImpl.java:304) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.toEntry(FhirResourceHandlerImpl.java:254) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
```

What I was able to find is that the draft state is set from the ProcessStateChangeOutcome of the ActivityDefinition in FhirResourceHandlerImpl line 98. 

I was able to add the Extension by incrementing the version number of the plugin and all my processes. I'm not sure if this is expected behavior for draft processes. Certainly it should not end in an NPE.

### PR DESCRIPTION
**Pull request by hhund**
Adds code for adding and removing FHIR resources from already deployed draft processes.

closes #165

### CODE REVIEW

**Review by wetret — APPROVED** [review]

File: dsf-fhir/dsf-fhir-server/src/test/java/org/highmed/dsf/fhir/integration/BinaryIntegrationTest.java [hunk 1]
```diff
@@ -1613,6 +1613,43 @@ public void testDelete() throws Exception
...
+		
+		assertNotNull(created.getSecurityContext());
+		assertEquals(createdOrg.getIdElement().toVersionless(), created.getSecurityContext().getReferenceElement());
+		
+		boolean deleted = binaryDao.delete(UUID.fromString(created.getIdElement().getIdPart()));
+		assertTrue(deleted);
+
+		getWebserviceClient().delete(Binary.class, created.getIdElement().getIdPart());
+		
+		binaryDao.read(UUID.fromString(created.getIdElement().getIdPart()));
```
Comment (wetret) [inline dsf-fhir/dsf-fhir-server/src/test/java/org/highmed/dsf/fhir/integration/BinaryIntegrationTest.java:1650]: I think this line does not return and throw the expected exception.

**Review by wetret — CHANGES_REQUESTED** [review]
Thank you for your changes. I think there is an error in the BinaryIntegrationTest#testDeleteDeleted() since the build does not finish and enters an endless loop (at least on my machine and in the GitHub runners). Can you check this?

File: dsf-fhir/dsf-fhir-server/src/test/java/org/highmed/dsf/fhir/integration/BinaryIntegrationTest.java (hunk 1 above)
Comment (hhund) [reply dsf-fhir/dsf-fhir-server/src/test/java/org/highmed/dsf/fhir/integration/BinaryIntegrationTest.java:1650]: hanging test based on bug in fhir client, fix see 1c17efe

**Review by wetret — APPROVED** [review]
